Fix non-existing branch error in section "Subversion to Git Transition"
Bioconductor/pkgrevdocs pull request #114
Opened 2023-10-17 08:16 UTC by mfasold

In the subsection "[Create a new GitHub repository for an existing Bioconductor package](https://contributions.bioconductor.org/git-version-control.html#maintain-github-bioc)" within "Subversion to Git Transition" of the git version control page, there is a problem in steps 8 /9 of the guide. 

The user clones an empty repo from GitHub. He will start in the branch `main`. In step 8, the aim is to merge upstreams `devel` branch with origins `devel` branch, and push those changes in step 9. As the user is in the `main` branch, those changes will be merged to `main`. And in step 9 there appears an error, as the `devel` branch does not exist. So one has to create and checkout a new `devel` branch in origin first.

2023-10-17 12:40 UTC, lshep commented
Would it be better however to just rename the default branch on github to devel so that they match and make it easier to push / pull to the same named branch instead of then having to do things like  `git push upstream main:devel` or `git pull upstream devel:main` .  It ERROR but the commands to fix it this main:devel are in the section right above that.   We made a blog about it --  https://blog.bioconductor.org/posts/2023-03-01-transition-to-devel/   -- maybe having/mentioning both options renaming and just checking out a new branch.

2024-05-02 18:59 UTC, LiNk-NY commented
I think we should add a note for those that don't use `devel` as the default branch:
`git branch -M devel` 
rather than checking out the `devel` branch

2024-05-02 19:01 UTC, LiNk-NY requested changes
It should probably be a note rather than recommending the user checkout the devel branch. We want to encourage that organizations use a `devel` branch as the default but also give the option to change the name of the branch if it is not the case.

2024-05-02 19:01 UTC, LiNk-NY commented on git-version-control.Rmd
> +        git checkout -b devel
Instead of this, add a note below it saying something like if the default branch is not devel use: 

```
git branch -M devel
```

2025-04-01 15:20 UTC, closed without merging